config/routes.rb
Rails.application.routes.draw do

  get 'home/configure'

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  get 'rutas/recorrido'
  get 'home/meinfo'

  resources :sections
  resources :articles
  resources :recorridos

  get 'home/index'

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  ###Lista los tres primeros articulos en caso de que existan
  def index
    @Articles=Article.all
    #@Articles.sort{ |a,b| a.article_date <=> a.article_date }
    @Articulos=[]
    for line in (0...3)
      if  @Articles[line] then
        @Articulos << @Articles[line]
      end
    end
  end

  ###Permite la Visualizacion de un Articulo en Especifico
  def show
    @Articulo = Article.find(params[:id])
  end

  def configure
    @Articles=Article.all
    @Recorridos=Recorrido.all
    @Sections=Section.all
    @Users=User.all
  end
end ##Fin de Controlador

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/configure.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="page-header">
        <h1>Listado de Articulos <small>Administracion</small></h1>
      </div>
      <%if can? :create, @article %>
        <%= link_to 'Nuevo Articulo', new_article_path,class:" pull-right btn btn-primary" %>
        <br>
        <br>
      <%end%>
      <div class="me_content_table">
        <table class="table table-striped table-condensed table-hover">
          <thead>
            <tr class="active">
              <th>Imagen</th>
              <th>Titulo</th>
              <th>Sub-Titulo</th>
              <!-- <th>Contenido</th> -->
              <th>Fecha</th>
              <th>Categoria</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @Articles.each do |article| %>
              <tr>
                <th><%= image_tag article.image.url(:thumb) %></th>
                <td><%= article.article_title %></td>
                <td><%= article.article_subtitle %></td>
                <!-- <td><%= raw article.article_content[0...281] %></td> -->
                <td><%= article.article_date %></td>
                <td><%= article.section.section_name %></td>
                <td><%= link_to 'Ver', article,class:"btn btn-default" %></td>
                <td><%= link_to 'Editar', edit_article_path(article),class:"btn btn-default" %></td>
                <td><%= link_to 'Borrar', article,class:"btn btn-default", method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="page-header">
        <h1>Listado de Recorridos <small>Administracion</small></h1>
        <%if can? :create, @recorrido %>
          <%= link_to 'Nuevo Recorrido', new_recorrido_path,class:"btn btn-primary pull-right" %>
          <br>
          <br>
        <%end%>
      </div>
      <div class="me_content_table">
        <table class="table table-striped  table-condensed table-hover">
          <thead>
            <tr class="active">
              <th>Nombre</th>
              <th>Descripcion</th>
              <th>Recorrido (GEOJson)</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @Recorridos.each do |recorrido| %>
              <tr>
                <td><%= recorrido.ruta_name %></td>
                <td><%= recorrido.ruta_description %></td>
                <td><%= recorrido.ruta_recorrido[0..181] %></td>
                <td><%= link_to 'Ver', recorrido,class:"btn btn-default" %></td>
                <td><%= link_to 'Editar', edit_recorrido_path(recorrido),class:"btn btn-default" %></td>
                <td><%= link_to 'Eliminar', recorrido, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-default" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="me_content_table">
        <div class="page-header">
          <h1>Listado de Categorias<small> Administracion</small></h1>
          <%if can? :create, @section %>
            <%= link_to 'Nuevo Categoria', new_section_path ,class:"btn btn-primary pull-right"%>
            <br>
            <br>
          <%end%>
        </div>
        <table class="table table-striped  table-condensed table-hover">
          <thead>
            <tr class="active">
              <th>Nombre</th>
              <th>Descripcion</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @Sections.each do |section| %>
              <tr>
                <td><%= section.section_name %></td>
                <td><%= section.section_description %></td>
                <td><%= link_to 'Ver', section,class:"btn btn-default" %></td>
                <td><%= link_to 'Editar', edit_section_path(section),class:"btn btn-default" %></td>
                <td><%= link_to 'Eliminar', section, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-default" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>


  </div>
</div>

app/views/home/index.html.erb
<section class="jumbotron jumbotron-fm">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12">
        <h1>Rutas de Managua</h1>
        <p>En este Blog Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima illo dolores ullam minus consectetur, repudiandae. Modi libero natus illo doloremque, excepturi nobis corporis optio ratione quas neque cumque sapiente iste?</p>
      </div>
    </div>
  </div>
</section>

<section class="main container">
<div class="row">
<!--Aqui va nuestro contenido principal-->
    <div class="posts col-md-9">
      <div class="migas-de-pan">
        <ol class="breadcrumb">
          <li><a href="#"><span class="glyphicon glyphicon-home"></span> Inicio</a></li>
        </ol>
      </div>

      <div id="mArticles">
        <% @Articulos.each do |articulo| %>
            <article class="post clearfix">
              <a href="#" class="thumb pull-left">
                <!-- <img src="<%= asset_path 'image2.jpg' %>" alt="Imagen numero uno" class="img-thumbnail"> -->
                <%= image_tag articulo.image.url(:small) ,class:"img-thumbnail" %>

              </a>

              <h2 class="post-title">
                <a href="#"><%= articulo.article_title%></a>
              </h2>
              <p><span class="post-fecha"><%= articulo.article_date%></span> Por <span class="post-autor"><a href="#">RutasManagua</a></span></p>
              <p class="post-contenido text-justify">
                <%=  articulo.article_content[0...281]+'...'%>
              </p>
              <div class="contenedor-botones">
                <%= link_to 'Leer mas', articulo,class:"btn btn-primary" %>
                <a href="#" class="btn btn-danger">Comentarios <span class="badge">20</span></a>
              </div>
            </article>
        <% end %>
      </div>

      <nav>
        <div class="center-block">
          <ul class="pagination">
            <li class="disabled"><a href="#">&laquo; <span class="sr-only">Anterior</span></a></li>
            <li class="Active"><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li><a href="#">&raquo; <span class="sr-only">Siguiente</span></a></li>
          </ul>
        </div>
      </nav>
    </div>
<!--Aqui va nuestro Aside-->
    <aside class="col-md-3 hidden-xs hidden-sm">
      <h4>Servicios</h4>
      <div class="list-group">
        <a href="#" class="list-group-item active">Recorridos</a>
        <a href="#" class="list-group-item">Ubicacion</a>
        <a href="#" class="list-group-item">Noticias</a>
        <a href="#" class="list-group-item">Contactenos</a>
      </div>

      <h4>Articulos Recientes</h4>
      <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">
          No tengo mas Patria que tu Corazon
        </h4>
        <p class="list-group-item-text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita repellendus animi.
        </p>
      </a>
      <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">
          todo comienzo es dificil
        </h4>
        <p class="list-group-item-text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, sunt, tempora. Labore aperiam.
        </p>
      </a>
      <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">
          Inicia porque de lo contrario no terminaras
        </h4>
        <p class="list-group-item-text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione fugit tenetur, quibusdam.
        </p>
      </a>
    </aside>
  </div>
</section>

app/views/home/meinfo.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 col-sm-12">
      <ol class="breadcrumb">
        <li><a href="#">Inicio</a></li>
        <li class="active">Quienes Somos</li>
      </ol>
      <article class="post clearfix">
        <div class="page-header">
            <h2>Misión <small>RutasManagua</small></h2>
        </div>
        <div class="contentPageHeader text-justify">
            <a href="<%= asset_path 'icon-mision.jpg' %>" class="thumb thumbnail pull-left">
                <img src="<%= asset_path 'icon-mision.jpg' %>" alt="Mision RutasManagua Image">
            </a>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
        </div>
      </article>

      <article class="post clearfix">
        <div class="page-header clear-fix">
            <h2>Visión <small>RutasManagua</small></h2>
        </div>
        <div class="contentPageHeader text-justify">
            <a href="<%= asset_path 'icon-vision.jpg' %>" class="thumb thumbnail pull-left">
                <img src="<%= asset_path 'icon-vision.jpg' %>" alt="Mision RutasManagua Image">
            </a>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
        </div>
      </article>

    </div>
    <div class="col-md-3 hidden-xs">
      <aside class="hidden-xs hidden-sm">
          <h4>Servicios</h4>
          <div class="list-group">
            <a href="#" class="list-group-item active">Mapas de Recorridos</a>
            <a href="#" class="list-group-item">Ubicacion</a>
            <a href="#" class="list-group-item">Noticas</a>
            <a href="#" class="list-group-item">Contactar / Sugerencias</a>
            <a href="#" class="list-group-item">Acerca de Nosotros</a>
          </div>
      </aside>
    </div>
  </div>
</div>