config/routes.rb
Rails.application.routes.draw do

  get 'home/configure'

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  get 'rutas/recorrido'
  get 'home/meinfo'

  resources :sections
  resources :articles
  resources :recorridos

  get 'home/index'

  root 'home#index'

end

app/models/section.rb
class Section < ActiveRecord::Base
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:section_name)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field col-xs-12">
      <%= f.label :section_name %><br>
      <%= f.text_field :section_name,class:"form-control" %>
    </div>

    <div class="field col-xs-12" style="margin-bottom:15px;">
      <%= f.label :'Descripcion' %><br>
      <%= f.text_area :section_description,class:"form-control box-info",id:"informacion" %>
    </div>

    <br>
    <br>

    <div class="actions">
      <%= f.submit  class:"btn btn-info pull-right"%>
    </div>
<% end %>

app/views/sections/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <h1>Editando Categoria o Seccion de Articulos</h1>

      <%= render 'form' %>

      <%= link_to 'Ver Contenido', @section,class:"btn btn-success" %> |
      <%= link_to 'Regresar', sections_path,class:"btn btn-danger"%>
    </div>
    <aside class="col-md-3 hidden-xs hidden-sm">
      <h4>Servicios</h4>
      <div class="list-group">
        <a href="#" class="list-group-item active">Curiosidades</a>
        <a href="#" class="list-group-item">Computadoras</a>
        <a href="#" class="list-group-item">Celulares</a>
        <a href="#" class="list-group-item">Diseño Web</a>
      </div>

      <h4>Articulos Recientes</h4>
      <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">
          No tengo mas Patria que tu Corazon
        </h4>
        <p class="list-group-item-text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita repellendus animi.
        </p>
      </a>
      <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">
          todo comienzo es dificil
        </h4>
        <p class="list-group-item-text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, sunt, tempora. Labore aperiam.
        </p>
      </a>
      <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">
          Inicia porque de lo contrario no terminaras
        </h4>
        <p class="list-group-item-text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione fugit tenetur, quibusdam.
        </p>
      </a>
    </aside>
  </div>
</div>

app/views/sections/index.html.erb
<div class="container">
    <p id="notice"><%= notice %></p>
    <div class="row">
      <div class="col-md-9">
        <div class="page-header">
          <h1>Categorias de Articulos</h1>
        </div>
        <div class="me_content_table">
          <table class="table table-striped  table-condensed table-hover">
            <thead>
              <tr class="active">
                <th>Nombre</th>
                <th>Descripcion</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @sections.each do |section| %>
                <tr>
                  <td><%= section.section_name %></td>
                  <td><%= section.section_description %></td>
                  <td><%= link_to 'Ver', section,class:"btn btn-default" %></td>
                  <td><%= link_to 'Editar', edit_section_path(section),class:"btn btn-default" %></td>
                  <td><%= link_to 'Eliminar', section, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-default" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <br><br>
        <%= link_to 'Nuevo Categoria', new_section_path ,class:"btn btn-info"%>
        <br><br>
      </div>

      <aside class="col-md-3 hidden-xs hidden-sm">
        <h4>Servicios</h4>
        <div class="list-group">
          <a href="#" class="list-group-item active">Curiosidades</a>
          <a href="#" class="list-group-item">Computadoras</a>
          <a href="#" class="list-group-item">Celulares</a>
          <a href="#" class="list-group-item">Diseño Web</a>
        </div>

        <h4>Articulos Recientes</h4>
        <a href="#" class="list-group-item">
          <h4 class="list-group-item-heading">
            No tengo mas Patria que tu Corazon
          </h4>
          <p class="list-group-item-text">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita repellendus animi.
          </p>
        </a>
        <a href="#" class="list-group-item">
          <h4 class="list-group-item-heading">
            todo comienzo es dificil
          </h4>
          <p class="list-group-item-text">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, sunt, tempora. Labore aperiam.
          </p>
        </a>
        <a href="#" class="list-group-item">
          <h4 class="list-group-item-heading">
            Inicia porque de lo contrario no terminaras
          </h4>
          <p class="list-group-item-text">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione fugit tenetur, quibusdam.
          </p>
        </a>
      </aside>

    </div>
</div>

app/views/sections/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <h1>Editando Categoria o Seccion de Articulos</h1>

      <%= render 'form' %>

      <%= link_to 'Regresar', sections_path,class:"btn btn-danger" %>
    </div>
    <aside class="col-md-3 hidden-xs hidden-sm">
      <h4>Servicios</h4>
      <div class="list-group">
        <a href="#" class="list-group-item active">Curiosidades</a>
        <a href="#" class="list-group-item">Computadoras</a>
        <a href="#" class="list-group-item">Celulares</a>
        <a href="#" class="list-group-item">Diseño Web</a>
      </div>

      <h4>Articulos Recientes</h4>
      <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">
          No tengo mas Patria que tu Corazon
        </h4>
        <p class="list-group-item-text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita repellendus animi.
        </p>
      </a>
      <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">
          todo comienzo es dificil
        </h4>
        <p class="list-group-item-text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, sunt, tempora. Labore aperiam.
        </p>
      </a>
      <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">
          Inicia porque de lo contrario no terminaras
        </h4>
        <p class="list-group-item-text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione fugit tenetur, quibusdam.
        </p>
      </a>
    </aside>
  </div>
</div>

app/views/sections/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9">

      <div class="migas-de-pan">
        <ol class="breadcrumb">
          <li><a href="#"><span class="glyphicon glyphicon-home"></span> Inicio</a></li>
          <li><a href="#">Categorias o Secciones de Articulos</a></li>
          <li><a href="#"><%= @section.section_name %></a></li>
        </ol>
      </div>

      <div class="page-header col-xs-12" style="margin-top:0px;">
        <h2>
          <%= @section.section_name %>
        </2>
      </div>
      <div class="col-xs-12">
        <%= @section.section_description %>
      </div>
      <br>
      <br>
      <div class="col-xs-12" style="margin-top:15px;">
        <div class="right">
          <%= link_to 'Editar', edit_section_path(@section),class:"btn btn-warning" %>
          <%= link_to 'Regresar', sections_path,class:"btn btn-danger" %>
        </div>
      </div>
      <br>
      <br>
      <br>
    </div>

    <aside class="col-md-3 hidden-xs hidden-sm">
      <h4>Servicios</h4>
      <div class="list-group">
        <a href="#" class="list-group-item active">Curiosidades</a>
        <a href="#" class="list-group-item">Computadoras</a>
        <a href="#" class="list-group-item">Celulares</a>
        <a href="#" class="list-group-item">Diseño Web</a>
      </div>

      <h4>Articulos Recientes</h4>
      <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">
          No tengo mas Patria que tu Corazon
        </h4>
        <p class="list-group-item-text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita repellendus animi.
        </p>
      </a>
      <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">
          todo comienzo es dificil
        </h4>
        <p class="list-group-item-text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, sunt, tempora. Labore aperiam.
        </p>
      </a>
      <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">
          Inicia porque de lo contrario no terminaras
        </h4>
        <p class="list-group-item-text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione fugit tenetur, quibusdam.
        </p>
      </a>
    </aside>


  </div>

</div>