config/routes.rb
Rails.application.routes.draw do

  get 'home/configure'

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  get 'rutas/recorrido'
  get 'home/meinfo'

  resources :sections
  resources :articles
  resources :recorridos

  get 'home/index'

  root 'home#index'

end

app/models/recorrido.rb
class Recorrido < ActiveRecord::Base
end

app/controllers/recorridos_controller.rb
class RecorridosController < ApplicationController
  before_action :set_recorrido, only: [:show, :edit, :update, :destroy]

  # GET /recorridos
  # GET /recorridos.json
  def index
    @recorridos = Recorrido.all
  end

  # GET /recorridos/1
  # GET /recorridos/1.json
  def show
  end

  # GET /recorridos/new
  def new
    @recorrido = Recorrido.new
  end

  # GET /recorridos/1/edit
  def edit
  end

  # POST /recorridos
  # POST /recorridos.json
  def create
    @recorrido = Recorrido.new(recorrido_params)

    respond_to do |format|
      if @recorrido.save
        format.html { redirect_to @recorrido, notice: 'Recorrido was successfully created.' }
        format.json { render :show, status: :created, location: @recorrido }
      else
        format.html { render :new }
        format.json { render json: @recorrido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recorridos/1
  # PATCH/PUT /recorridos/1.json
  def update
    respond_to do |format|
      if @recorrido.update(recorrido_params)
        format.html { redirect_to @recorrido, notice: 'Recorrido was successfully updated.' }
        format.json { render :show, status: :ok, location: @recorrido }
      else
        format.html { render :edit }
        format.json { render json: @recorrido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recorridos/1
  # DELETE /recorridos/1.json
  def destroy
    @recorrido.destroy
    respond_to do |format|
      format.html { redirect_to recorridos_url, notice: 'Recorrido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recorrido
      @recorrido = Recorrido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recorrido_params
      params.require(:recorrido).permit(:ruta_name, :ruta_description, :ruta_recorrido)
    end
end

app/helpers/recorridos_helper.rb
module RecorridosHelper
end

app/views/recorridos/_form.html.erb
<div class="">
  <div class="row">
    <div class="col-md-9 col-xs-12">
        <%= form_for(@recorrido) do |f| %>
          <% if @recorrido.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@recorrido.errors.count, "error") %> prohibited this recorrido from being saved:</h2>

              <ul>
              <% @recorrido.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= f.label :Nombre %><br>
            <%= f.text_field :ruta_name,class:"form-control" %>
          </div>
          <div class="field">
            <%= f.label :Descripcion %><br>
            <%= f.text_area :ruta_description,class:"form-control" %>
          </div>
          <div class="field">
            <%= f.label :Recorrido %><br>
            <%= f.text_area :ruta_recorrido,class:"form-control box-info",id:"informacion" %>
          </div>
          <div class="actions pull-right" style="margin-top:20px;">
            <%= f.button 'Guardar',class:"btn btn-primary" %>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/recorridos/edit.html.erb
<div class="container">
  <h1>Editando Recorrido</h1>

  <%= render 'form' %>

  <div class="col-xs-12">
    <%= link_to 'Ver', @recorrido,class:"btn btn-success" %> |
    <%= link_to 'Regresar', recorridos_path,class:"btn btn-danger" %>
  </div>
  <br>
  <br>
</div>

app/views/recorridos/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Lista de Recorridos</h1>

  <div class="me_content_table">
    <table class="table table-striped  table-condensed table-hover">
      <thead>
        <tr class="active">
          <th>Nombre</th>
          <th>Descripcion</th>
          <th>Recorrido (GEOJson)</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @recorridos.each do |recorrido| %>
          <tr>
            <td><%= recorrido.ruta_name %></td>
            <td><%= recorrido.ruta_description %></td>
            <td><%= recorrido.ruta_recorrido[0..181] %></td>
            <td><%= link_to 'Ver', recorrido,class:"btn btn-default" %></td>
            <td><%= link_to 'Editar', edit_recorrido_path(recorrido),class:"btn btn-default" %></td>
            <td><%= link_to 'Eliminar', recorrido, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-default" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <%= link_to 'Nuevo Recorrido', new_recorrido_path,class:"btn btn-primary" %>
</div>

app/views/recorridos/new.html.erb
<div class="container">
  <h1>Nuevo Recorrido</h1>

  <%= render 'form' %>

  <%= link_to 'Back', recorridos_path,class:"btn btn-danger" %>
</div>

app/views/recorridos/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-9">
      <% if notice %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
      <% end %>


      <div class="page-header">
        <h1>Recorrido <%= @recorrido.ruta_name %> <small>Mapa</small></h1>
      </div>

      <div class="col-xs-12">
        <div style="width:100%; height:100%" id="map"></div>
      </div>

      <div class="col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Descripcion</h3>
          </div>
          <div class="panel-body">
            <%= @recorrido.ruta_description %>
          </div>
        </div>
      </div>

      <div class="col-xs-12">
        <div class="col-xs-8">

        </div>
        <div class="col-xs-4 pull-right text-right">
          <%= link_to 'Editar', edit_recorrido_path(@recorrido),class:"btn btn-success" %> |
          <%= link_to 'Regresar', recorridos_path,class:"btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  var geojsonObjectString=<%= raw @recorrido.ruta_recorrido.to_json %>;
    if (geojsonObjectString)
    {
      var vectorSource = new ol.source.Vector({
        features: (new ol.format.GeoJSON()).readFeatures(geojsonObjectString,{
          dataProjection: 'EPSG:4326',
          featureProjection: 'EPSG:3857'
            })
      });

      var vectorLayer = new ol.layer.Vector({
        source: vectorSource,
      });

      var map = new ol.Map({
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          }),
          vectorLayer
        ],
        target: 'map',
        controls: ol.control.defaults({
          attributionOptions: /** @type {olx.control.AttributionOptions} */ ({
            collapsible: false
          })
        }),
        view: new ol.View({
          defaultDataProjection: 'EPSG:4326',
          center: ol.proj.transform([-86.25040, 12.13282], 'EPSG:4326', 'EPSG:3857'),
          zoom: 13
        })
      });
    } else {
      var map = new ol.Map({
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          })
        ],
        target: 'map',
        controls: ol.control.defaults({
          attributionOptions: /** @type {olx.control.AttributionOptions} */ ({
            collapsible: false
          })
        }),
        view: new ol.View({
          defaultDataProjection: 'EPSG:4326',
          center: ol.proj.transform([-86.25040, 12.13282], 'EPSG:4326', 'EPSG:3857'),
          zoom: 13
        })
      });
    }
</script>